### ISSUE TITLE
not working on macOS 10.12.6

### ISSUE THREAD

**Issue by sunt05** [hansec/ide-fortran#1]
I know this information might be useless to the developer, but I still want to report it.
My system:
OS: 10.12.6
Atom: 1.21.1

No any feature available at my side.
![screenshot 2017-10-22 20 24 34](https://user-images.githubusercontent.com/1802656/31865452-0d75c168-b767-11e7-88bc-f0ec8a9618fb.png)

I tried running `fortls` in terminal with some debug options, which, however, gave reasonable results.

Please let me know what other info you may need to detect the issue.

I'm keen to get this running on my machine.

**Comment by hansec** [comment]
Thanks for the feedback! I just pushed an update to the [language server](https://github.com/hansec/fortran-language-server) (`fortls`) that may fix the problem you are seeing. Can you try updating updating the language server and see if that fixes things?

If it does not, can you try the following things and let me know what the results are:

1. Write a very simple FORTRAN file with a single module and contained subroutine to see if that works. Make sure to do this in a directory with no other source files and open it in a new Atom window.
2. Place the file from your screenshot above in a directory with no other source files and open it in a new Atom window.

Those test should help me narrow down the issue.

**Comment by sunt05** [comment]
Thanks very much for your quick response!
It seems working now: for small projects with several files, it works well; whereas for larger ones, error info pops out saying the parser failed on some files and then `fortls` will stop working.
![screenshot 2017-10-23 22 39 00](https://user-images.githubusercontent.com/1802656/31914541-00d03722-b843-11e7-8129-acb919e052e7.png)
I would consider it as a performance issue common for Atom rather than your plugin, but I will report other issues if any to make this work more useful.

Thanks again for your work!

**Comment by hansec** [comment]
I am glad this got things working for some of your cases. The parsing issues are definitely related to the Fortran language server, not Atom in general. If you can send me a link to the source files that are reporting errors I would be happy to try and fix the issues the parser is having. The more source code examples I can test with the better.

**Comment by hansec** [comment]
I found one other common issue that may be causing the remaining parser failures you are seeing. It is now available in `fortls` version 0.1.4.

In the future if you run into more parsing failures please feel free to open an issue on [fortls](https://github.com/hansec/fortran-language-server). I'd be happy to try and track down the issue. Thanks again for the feedback.

**Comment by sunt05** [comment]
Thanks, @hansec! As those pieces of code belong to my colleagues and are currently closed source, I cannot send them to you for investigation at the moment. But once I got the permission or I come across the issue with my own code, I'll share them with you to improve the plugin.

**Comment by sunt05** [comment]
Just updated `fortls` to version 0.1.4 and I confirm this issue has been resolved at my side.
