### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by gronemeier** [hansec/ide-fortran#10]
Dear all,
when installing the package, I receive the following error:
>'fortls' could not be spawned. Is it installed and on your path? If so please open an issue on the package spawning the process.

My configuration:
* Atom, Version 1.31.2
* Installed packages: 
  * language-fortran, Version 2.1.7
  * atom-ide-ui, Version 0.13.0
* Windows 10, Version 10.0.17134 Build 17134

**Comment by gronemeier** [comment]
I just came across the following error message when opening a Fortran file:

> Unable to start the FORTRAN language server.
This can occur if you do not have Python installed or if it is not in your path.
Also, make sure to install fortls by running:
```pip install fortran-language-server```

> fortls language server for Fortran unable to start
```Error: spawn fortls ENOENT```

I guess that this is related to the error message which occurred during installation.

Now, I wonder if the missing ```fortran-language-server``` should be added to the requirements list of the package. Or is this part of the 'language-fortran' package? If so, then there is a bug in the package as the 'language-fortran' package is installed and working.

**Comment by hansec** [comment]
Unfortunately, the language server must be installed separately outside of the Atom package installation process. This is mentioned in the [README](https://github.com/hansec/ide-fortran#requirements).

As the error you received mentions you must install the [fortran language server](https://github.com/hansec/fortran-language-server), which can be done using `pip` as described. Unfortunately, as the language server is a Python package there is no easy way to have it automatically installed like the other Atom package dependencies. If you run into issues after installing the language server or with that process let me know.

**Comment by hansec** [comment]
As it has been awhile I am going to assume this issue was resolved by installing the language server separately. If you are still having issues getting the extension working let me know.
