### ISSUE TITLE
Recursively add source folders

### ISSUE THREAD

**Issue by Poolshark** [hansec/ide-fortran#2]
First of all, great work!

I was womdering if there would be a way to add source folders containing Fortran files recursively instead of adding them all in a .fortls file?

Unfortunately I have no clue how to do that but I'm willing to help if you tell me how to accomplish something like that (if even possible).

Thanks!

**Comment by hansec** [comment]
I actually have this implemented already. I just haven't pushed the changes to the [Language Server](https://github.com/hansec/fortran-language-server) yet. I will close this issue when I have pushed that upgrade to PyPi (pip). It will probably be in the next few days.

**Comment by hansec** [comment]
This capability is now available in `fortls` [v0.2.0](https://github.com/hansec/fortran-language-server/releases/tag/v0.2.0). Just update the [fortran-language-server](https://github.com/hansec/fortran-language-server) using `pip` or your preferred method and you should get it. Check out the README for that package to see information on the new configuration options.
