### ISSUE TITLE
Uncaught Error: Header must provide a Content-Length property.

### ISSUE THREAD

**Issue by sunt05** [hansec/ide-fortran#5]
[Enter steps to reproduce:]

1. Launch Atom by opening a Fortran file.

**Atom**: 1.26.1 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.4
**Thrown From**: [ide-fortran](https://github.com/hansec/ide-fortran) package 0.1.5

### Stack Trace

Uncaught Error: Header must provide a Content-Length property.

```
At /Users/sunt05/.atom/packages/ide-fortran/node_modules/vscode-jsonrpc/lib/messageReader.js:200

Error: Header must provide a Content-Length property.
    at StreamMessageReader.onData (/packages/ide-fortran/node_modules/vscode-jsonrpc/lib/messageReader.js:200:27)
    at /packages/ide-fortran/node_modules/vscode-jsonrpc/lib/messageReader.js:185:19)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

### Commands

```
```

### Non-Core Packages

```
atom-alignment 0.13.0 
atom-beautify 0.32.2 
atom-html-preview 0.2.5 
atom-ide-ui 0.11.1 
atom-live-server 2.2.0 
atom-rst-preview-docutils 1.0.0 
atom-transpose 0.3.5 
auto-update-packages 1.0.1 
autocomplete-python 1.10.5 
browser-plus 0.0.98 
build 0.70.0 
build-make 0.13.0 
busy 0.7.0 
busy-signal 1.4.3 
city-lights-syntax 1.1.8 
city-lights-ui 1.3.3 
dash 1.7.1 
expand-region 0.4.0 
git-plus 7.10.2 
git-time-machine 1.5.9 
goto-mathematica 0.3.1 
gpp-compiler 3.0.7 
highlight-line 0.12.0 
highlight-selected 0.13.1 
Hydrogen 2.4.1 
hydrogen-launcher 1.2.2 
ide-fortran 0.1.5 
ide-python 0.9.2 
intentions 1.1.5 
language-csv 1.1.2 
language-fortran 2.1.6 
language-lisp 0.2.0 
language-markdown 0.25.1 
language-mathematica 0.3.2 
language-matlab 0.2.1 
language-mediawiki 2.2.0 
language-ncl 0.3.0 
language-r 0.4.2 
language-restructuredtext 1.1.2 
language-sphinx 0.1.6 
last-cursor-position 0.9.2 
linter 2.2.0 
linter-gcc 0.7.1 
linter-gfortran 0.5.0 
linter-matlab 1.1.0 
linter-shellcheck 1.4.7 
linter-ui-default 1.7.1 
make-runner 1.1.15 
markdown-table-formatter 2.9.2 
minimap 4.29.8 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-linter 2.1.3 
minimap-selection 4.5.0 
multi-cursor 2.1.5 
open-recent 5.0.0 
pandoc 0.2.2 
pandoc-convert 1.1.1 
pdf-view 0.69.0 
platformio-ide-terminal 2.8.1 
python-autopep8 0.1.3 
python-debugger 0.2.0 
rst-preview-pandoc 0.1.12 
script 3.17.3 
sphinx-preview 0.1.1 
split-diff 1.5.2 
Sublime-Style-Column-Selection 1.7.4 
sync-settings 0.8.6 
tablr 1.8.3 
tabularize 0.2.5 
teletype 0.13.2 
todo-show 2.3.0 
```

**Comment by hansec** [comment]
Thanks for the report. This sounds like a crash of the language server. Can you try [running the language server in debug mode](https://github.com/hansec/fortran-language-server/wiki/Debugging-server-initialization-errors) with the root directory where you encounter the error? Also, please verify you are using the newest version (0.3.5) of the [language server](https://github.com/hansec/fortran-language-server).

**Comment by sunt05** [comment]
Hi, thanks for your guidance for the debug testing.
I'm using the latest `fortls` (0.3.5) and the debug information is as follows:
    
    
    Testing "initialize" request:
    Root = "/Users/sunt05/Dropbox/8-Research/98.ReadingWork/10.SUEWS-FORTRAN"
     Succesful
     Found module directories:
    /Users/sunt05/Dropbox/8-Research/98.ReadingWork/10.SUEWS-FORTRAN/Archive
    /Users/sunt05/Dropbox/8-Research/98.ReadingWork/10.SUEWS-FORTRAN/Archive/SOLWEIG
    /Users/sunt05/Dropbox/8-Research/98.ReadingWork/10.SUEWS-FORTRAN/SUEWS-SourceCode
    /Users/sunt05/Dropbox/8-Research/98.ReadingWork/10.SUEWS-FORTRAN/build/src.macosx-10.13-x86_64-3.6/supy
    /Users/sunt05/Dropbox/8-Research/98.ReadingWork/10.SUEWS-FORTRAN/build/src.macosx-10.13-x86_64-2.7/supy

**Comment by hansec** [comment]
Hmmmm, I expected that to tell us something (probably throw an error). Does this problem occur for every project you test or just the "SUEWS" source code? Without source code it is hard to debug. Can you [look at the debug log for the language server](https://github.com/hansec/ide-fortran/wiki/Debugging-ide-fortran) to try and determine what request/file the exception is occurring on?

**Comment by hansec** [comment]
I am going to go ahead and close this issue since its been a month. If you continue to experience the problem let me know.
