### ISSUE TITLE
Causing System Lockup

### ISSUE THREAD

**Issue by everythingfunctional** [hansec/ide-fortran#6]
It appears that when this plugin starts, it launches a process that uses 100% cpu and does not end.

The process is `$SHELL -ilc env; exit`. If I manually kill that process then everything works fine.

With some quick research I found at least one other plugin was having a similar problem. See the following issues:

* https://github.com/Glavin001/atom-beautify/issues/1733
* https://github.com/Glavin001/atom-beautify/issues/1728

I was able to narrow it down to ide-fortran because it only happened when I opened a fortran file, and when I disabled ide-fortran it didn't happen.

Just FYI I'm running Atom 1.26.1 on Arch, using zsh. But I've also seen the problem running on Ubuntu using bash.

**Comment by hansec** [comment]
Thanks for the report. This is likely an issue with the language server. Can you [try running the language server in debug mode](https://github.com/hansec/fortran-language-server/wiki/Debugging-server-initialization-errors) with the same root directory as the Atom project you are using when you encounter the error.

A couple more questions:
  1) Does this happen with every fortran file/project or just some files and/or projects.
  2) When you say "If I manually kill that process then everything works fine", do you still see an outline for the fortran file and do you see an error messages when you kill that process?

**Comment by hansec** [comment]
Actually, thanks to your research I think I have tracked down the problem. It is due to how I am launching the language server from Atom. I will release the fix shortly. Thanks again!

**Comment by hansec** [comment]
I have now published this fix in a release. Let me know if you continue to encounter issues after updating. Thanks again for the report!

**Comment by everythingfunctional** [comment]
That seems to have solved the problem. Thanks a bunch.
