### ISSUE TITLE
Integer type does not work properly.

### ISSUE THREAD

**Issue by sishue** [hansec/ide-fortran#8]
The hover shows nothing for integer type variables. And the outline and autocompletion have no information for integer members of derived types.

**Comment by hansec** [comment]
Thanks for the report. Can you post some example code and a screenshot of where you see this issue? Also, just to confirm everything works correctly for non-integer variables like “REAL”?

**Comment by sishue** [comment]
Hello Hansec,

I just tested the ide-fortran with very basis code like:
program main
implicit none
    integer:: int1, int2
    real(8):: r1, r2
    real:: f1, f2
    complex:: c1, c2
    complex(8):: cc1, cc2

    int1 = 1
    int2 = 2
    r1 = 1.0
    r2 = 2.0
    f1 = r1
    f2 = r2
    c1 = r1
    c2 = r2
    cc1 = c1

    print*,int1,int2,r1,r2,c1,c2
end program main

I found that: real(8) and complex(8) can work correctly, however, integer, real, and complex all fail.

Thankyou,
Sixue

**Comment by hansec** [comment]
Ok, I think I found the issue causing this in the underlying language server. I just added the fix to a new release (0.7.2). Update the language server and let me know if you keep seeing the issue. Thanks again for the report.
